export enum Images {
	BACKGROUND_V = 'background_v',
	BACKGROUND_H = 'background_h',
	NEPTUNE = 'Neptune',
	BOARD = 'board',
	BUTTON = 'button',
	BUTTON_FREE = 'buttonFree',
	BUTTON_LANG = 'buttonLang',
	BUTTON_SOUND = 'buttonSound',
	STAR = 'star',
	BUTTON_HOME = 'buttonHome',
	BUTTON_MENU = 'buttonMenu',
	LEFT = 'left',
	RIGHT = 'right',
	DOWN = 'down',
	UP = 'up',
	ENTER = 'enter',
	CELL_FREE = 'cellFree',
	POINTER = 'pointer',
	PLAY = 'play',
	CELL_X = 'cellX',
	CELL_ZERO = 'cellZero',
	CELL_X_HIGHLIGHTED = 'cellXHighlighted',
	CELL_ZERO_HIGHLIGHTED = 'cellZeroHighlighted',
	TEMPLATE_X = 'templateX',
	CONTOUR = 'contour'
}
